export type ConnectorStatus = "active" | "warning" | "error" | "inactive"
export type ConnectorCategory = "APM" | "Logs" | "Infra" | "API" | "Database" | "Synthetic" | "Incident" | "Messaging" | "Cloud" | "Custom"

export interface ConnectorInstance {
  id: string
  name: string
  template: string
  category: ConnectorCategory
  status: ConnectorStatus
  environment: string
  version: string
  lastSync: string
  healthScore: number
  usageCount: number
  appsConnected: number
  capabilities: string[]
  description: string
  bgColor: string
  iconBg: string
  abbr: string
}

export const CONNECTOR_INSTANCES: ConnectorInstance[] = [
  {
    id: "dd-prod",
    name: "Datadog (Production)",
    template: "Datadog",
    category: "APM",
    status: "active",
    environment: "Production",
    version: "v2.1.0",
    lastSync: "12s ago",
    healthScore: 99,
    usageCount: 1842,
    appsConnected: 42,
    capabilities: ["APM", "Metrics", "Traces", "Logs"],
    description: "Full-stack observability platform with APM, infrastructure metrics, and log management",
    bgColor: "from-violet-500/15 to-violet-500/5",
    iconBg: "bg-violet-500/10 text-violet-500",
    abbr: "DD",
  },
  {
    id: "prom-prod",
    name: "Prometheus (Production)",
    template: "Prometheus",
    category: "Infra",
    status: "active",
    environment: "Production",
    version: "v2.48.0",
    lastSync: "28s ago",
    healthScore: 96,
    usageCount: 3200000,
    appsConnected: 38,
    capabilities: ["Metrics", "Alerting", "Time Series"],
    description: "Open-source systems monitoring and alerting toolkit with multi-dimensional data model",
    bgColor: "from-orange-500/15 to-orange-500/5",
    iconBg: "bg-orange-500/10 text-orange-500",
    abbr: "PR",
  },
  {
    id: "cw-prod",
    name: "CloudWatch (AWS)",
    template: "AWS CloudWatch",
    category: "Cloud",
    status: "active",
    environment: "Production",
    version: "API v2",
    lastSync: "1m ago",
    healthScore: 98,
    usageCount: 9420,
    appsConnected: 29,
    capabilities: ["Metrics", "Logs", "Events", "Alarms"],
    description: "AWS native observability service for resources, applications, and services",
    bgColor: "from-amber-500/15 to-amber-500/5",
    iconBg: "bg-amber-500/10 text-amber-500",
    abbr: "CW",
  },
  {
    id: "splunk-prod",
    name: "Splunk Enterprise",
    template: "Splunk",
    category: "Logs",
    status: "warning",
    environment: "Production",
    version: "v9.2.1",
    lastSync: "18m ago",
    healthScore: 71,
    usageCount: 580000,
    appsConnected: 15,
    capabilities: ["Logs", "Search", "Dashboards", "Alerts"],
    description: "Enterprise data platform for log aggregation, search, and operational intelligence",
    bgColor: "from-green-500/15 to-green-500/5",
    iconBg: "bg-green-500/10 text-green-600",
    abbr: "SP",
  },
  {
    id: "appdyn-prod",
    name: "AppDynamics (Prod)",
    template: "AppDynamics",
    category: "APM",
    status: "active",
    environment: "Production",
    version: "v24.1",
    lastSync: "45s ago",
    healthScore: 94,
    usageCount: 2140,
    appsConnected: 18,
    capabilities: ["APM", "Business Transactions", "Server Monitoring"],
    description: "Application performance management with business transaction monitoring and AI anomaly detection",
    bgColor: "from-blue-500/15 to-blue-500/5",
    iconBg: "bg-blue-500/10 text-blue-500",
    abbr: "AD",
  },
  {
    id: "grafana-prod",
    name: "Grafana Cloud",
    template: "Grafana",
    category: "Infra",
    status: "active",
    environment: "Production",
    version: "v10.2",
    lastSync: "3m ago",
    healthScore: 92,
    usageCount: 4300,
    appsConnected: 22,
    capabilities: ["Dashboards", "Alerting", "Loki", "Tempo"],
    description: "Open-source visualization and monitoring platform with multi-source dashboard support",
    bgColor: "from-rose-500/15 to-rose-500/5",
    iconBg: "bg-rose-500/10 text-rose-500",
    abbr: "GF",
  },
  {
    id: "dynatrace-prod",
    name: "Dynatrace (Staging)",
    template: "Dynatrace",
    category: "APM",
    status: "active",
    environment: "Staging",
    version: "v1.291",
    lastSync: "2m ago",
    healthScore: 97,
    usageCount: 1200,
    appsConnected: 12,
    capabilities: ["APM", "Davis AI", "Infrastructure", "Digital Experience"],
    description: "AI-powered observability platform with automatic full-stack discovery and root cause analysis",
    bgColor: "from-teal-500/15 to-teal-500/5",
    iconBg: "bg-teal-500/10 text-teal-500",
    abbr: "DT",
  },
  {
    id: "pagerduty-prod",
    name: "PagerDuty",
    template: "PagerDuty",
    category: "Incident",
    status: "active",
    environment: "Production",
    version: "API v2",
    lastSync: "Just now",
    healthScore: 100,
    usageCount: 318,
    appsConnected: 34,
    capabilities: ["Incidents", "Escalations", "On-Call", "Postmortems"],
    description: "Digital operations management platform for incident response and on-call scheduling",
    bgColor: "from-emerald-500/15 to-emerald-500/5",
    iconBg: "bg-emerald-500/10 text-emerald-500",
    abbr: "PD",
  },
  {
    id: "kafka-prod",
    name: "Kafka Monitor",
    template: "Kafka / MQ",
    category: "Messaging",
    status: "active",
    environment: "Production",
    version: "v3.6.0",
    lastSync: "8s ago",
    healthScore: 88,
    usageCount: 820000,
    appsConnected: 9,
    capabilities: ["Queue Depth", "Consumer Lag", "Throughput", "Latency"],
    description: "Real-time message queue monitoring for Kafka clusters with consumer lag alerting",
    bgColor: "from-slate-500/15 to-slate-500/5",
    iconBg: "bg-slate-500/10 text-slate-500",
    abbr: "KF",
  },
  {
    id: "dbmon-prod",
    name: "Database Monitor",
    template: "Database Monitor",
    category: "Database",
    status: "warning",
    environment: "Production",
    version: "v1.4.2",
    lastSync: "12m ago",
    healthScore: 68,
    usageCount: 4800,
    appsConnected: 17,
    capabilities: ["Query Performance", "Connections", "Replication", "Locks"],
    description: "Deep database observability for Postgres, MySQL, and MongoDB with query-level insights",
    bgColor: "from-cyan-500/15 to-cyan-500/5",
    iconBg: "bg-cyan-500/10 text-cyan-500",
    abbr: "DB",
  },
  {
    id: "synth-prod",
    name: "Synthetic Health",
    template: "Synthetic Health",
    category: "Synthetic",
    status: "active",
    environment: "Production",
    version: "v2.0.1",
    lastSync: "5m ago",
    healthScore: 95,
    usageCount: 144,
    appsConnected: 24,
    capabilities: ["HTTP Probes", "SLA Tracking", "Geo Tests", "Flow Tests"],
    description: "Proactive synthetic monitoring for APIs and user flows with global test locations",
    bgColor: "from-pink-500/15 to-pink-500/5",
    iconBg: "bg-pink-500/10 text-pink-500",
    abbr: "SY",
  },
  {
    id: "logicmon-prod",
    name: "LogicMonitor",
    template: "LogicMonitor",
    category: "Infra",
    status: "error",
    environment: "Production",
    version: "v6.8",
    lastSync: "2h ago",
    healthScore: 0,
    usageCount: 0,
    appsConnected: 0,
    capabilities: ["Infrastructure", "Network", "Cloud", "Logs"],
    description: "Infrastructure monitoring platform with automated device discovery and hybrid observability",
    bgColor: "from-indigo-500/15 to-indigo-500/5",
    iconBg: "bg-indigo-500/10 text-indigo-500",
    abbr: "LM",
  },
]

export const CONNECTOR_TEMPLATES = [
  { id: "datadog", name: "Datadog", category: "APM" as ConnectorCategory, abbr: "DD", iconBg: "bg-violet-500/10 text-violet-500", description: "APM, metrics, traces and logs" },
  { id: "prometheus", name: "Prometheus", category: "Infra" as ConnectorCategory, abbr: "PR", iconBg: "bg-orange-500/10 text-orange-500", description: "Open-source metrics and alerting" },
  { id: "cloudwatch", name: "AWS CloudWatch", category: "Cloud" as ConnectorCategory, abbr: "CW", iconBg: "bg-amber-500/10 text-amber-500", description: "AWS native observability" },
  { id: "splunk", name: "Splunk", category: "Logs" as ConnectorCategory, abbr: "SP", iconBg: "bg-green-500/10 text-green-600", description: "Log aggregation and search" },
  { id: "appdynamics", name: "AppDynamics", category: "APM" as ConnectorCategory, abbr: "AD", iconBg: "bg-blue-500/10 text-blue-500", description: "Business transaction monitoring" },
  { id: "grafana", name: "Grafana", category: "Infra" as ConnectorCategory, abbr: "GF", iconBg: "bg-rose-500/10 text-rose-500", description: "Dashboards and visualization" },
  { id: "dynatrace", name: "Dynatrace", category: "APM" as ConnectorCategory, abbr: "DT", iconBg: "bg-teal-500/10 text-teal-500", description: "AI-powered full-stack APM" },
  { id: "pagerduty", name: "PagerDuty", category: "Incident" as ConnectorCategory, abbr: "PD", iconBg: "bg-emerald-500/10 text-emerald-500", description: "Incident response platform" },
  { id: "kafka", name: "Kafka / MQ", category: "Messaging" as ConnectorCategory, abbr: "KF", iconBg: "bg-slate-500/10 text-slate-500", description: "Message queue monitoring" },
  { id: "database", name: "Database Monitor", category: "Database" as ConnectorCategory, abbr: "DB", iconBg: "bg-cyan-500/10 text-cyan-500", description: "SQL/NoSQL query insights" },
  { id: "synthetic", name: "Synthetic Health", category: "Synthetic" as ConnectorCategory, abbr: "SY", iconBg: "bg-pink-500/10 text-pink-500", description: "Proactive synthetic probing" },
  { id: "custom", name: "Custom REST API", category: "Custom" as ConnectorCategory, abbr: "CR", iconBg: "bg-muted text-muted-foreground", description: "Any HTTP/REST endpoint" },
]

export const CATEGORIES: ConnectorCategory[] = ["APM", "Logs", "Infra", "API", "Database", "Synthetic", "Incident", "Messaging", "Cloud", "Custom"]
