import random
import math
from datetime import datetime, timedelta

TEAMS = [
    {"id": "platform", "name": "Platform Engineering", "tier": 1, "lead_name": "Alex Chen", "slack_channel": "#platform-eng", "description": "Core platform infrastructure and tooling", "health_score": 96.2, "incident_count": 1},
    {"id": "payments", "name": "Payments", "tier": 1, "lead_name": "Sarah Kim", "slack_channel": "#payments-eng", "description": "Payment processing and billing services", "health_score": 91.4, "incident_count": 2},
    {"id": "commerce", "name": "Commerce", "tier": 1, "lead_name": "Marcus Johnson", "slack_channel": "#commerce-eng", "description": "Shopping, catalog, and order management", "health_score": 88.7, "incident_count": 3},
    {"id": "discovery", "name": "Search & Discovery", "tier": 2, "lead_name": "Priya Patel", "slack_channel": "#search-eng", "description": "Search, recommendations, and indexing", "health_score": 72.1, "incident_count": 2},
    {"id": "ml", "name": "Machine Learning", "tier": 2, "lead_name": "David Wu", "slack_channel": "#ml-eng", "description": "ML model serving and feature pipelines", "health_score": 85.3, "incident_count": 1},
    {"id": "logistics", "name": "Logistics", "tier": 2, "lead_name": "Elena Rodriguez", "slack_channel": "#logistics-eng", "description": "Shipping, tracking, and fulfillment", "health_score": 93.8, "incident_count": 0},
    {"id": "risk", "name": "Risk & Security", "tier": 1, "lead_name": "James Park", "slack_channel": "#risk-security", "description": "Fraud detection, compliance, and audit", "health_score": 97.1, "incident_count": 0},
    {"id": "analytics", "name": "Analytics & Data", "tier": 2, "lead_name": "Natasha Williams", "slack_channel": "#analytics-eng", "description": "Data pipelines, reporting, and warehousing", "health_score": 89.6, "incident_count": 1},
]

TEAM_MEMBERS = {
    "platform": [
        {"name": "Alex Chen", "initials": "AC", "role": "Staff Engineer", "email": "alex.chen@healthmesh.io", "on_call": True},
        {"name": "Jordan Blake", "initials": "JB", "role": "Senior SRE", "email": "jordan.blake@healthmesh.io", "on_call": False},
        {"name": "Morgan Lee", "initials": "ML", "role": "Backend Engineer", "email": "morgan.lee@healthmesh.io", "on_call": False},
        {"name": "Riley Foster", "initials": "RF", "role": "DevOps Engineer", "email": "riley.foster@healthmesh.io", "on_call": True},
    ],
    "payments": [
        {"name": "Sarah Kim", "initials": "SK", "role": "Engineering Manager", "email": "sarah.kim@healthmesh.io", "on_call": True},
        {"name": "Carlos Mendez", "initials": "CM", "role": "Senior Engineer", "email": "carlos.mendez@healthmesh.io", "on_call": False},
        {"name": "Aisha Osei", "initials": "AO", "role": "Backend Engineer", "email": "aisha.osei@healthmesh.io", "on_call": False},
        {"name": "Tom Hughes", "initials": "TH", "role": "SRE", "email": "tom.hughes@healthmesh.io", "on_call": False},
    ],
    "commerce": [
        {"name": "Marcus Johnson", "initials": "MJ", "role": "Tech Lead", "email": "marcus.j@healthmesh.io", "on_call": True},
        {"name": "Ling Zhao", "initials": "LZ", "role": "Senior Engineer", "email": "ling.zhao@healthmesh.io", "on_call": False},
        {"name": "Fatima Hassan", "initials": "FH", "role": "Backend Engineer", "email": "fatima.h@healthmesh.io", "on_call": True},
    ],
    "discovery": [
        {"name": "Priya Patel", "initials": "PP", "role": "Engineering Manager", "email": "priya.p@healthmesh.io", "on_call": True},
        {"name": "Ryan Nguyen", "initials": "RN", "role": "Search Engineer", "email": "ryan.n@healthmesh.io", "on_call": False},
        {"name": "Zoe Martinez", "initials": "ZM", "role": "ML Engineer", "email": "zoe.m@healthmesh.io", "on_call": False},
    ],
    "ml": [
        {"name": "David Wu", "initials": "DW", "role": "Principal ML Engineer", "email": "david.wu@healthmesh.io", "on_call": True},
        {"name": "Sophia Ivanova", "initials": "SI", "role": "ML Engineer", "email": "sophia.i@healthmesh.io", "on_call": False},
    ],
    "logistics": [
        {"name": "Elena Rodriguez", "initials": "ER", "role": "Tech Lead", "email": "elena.r@healthmesh.io", "on_call": True},
        {"name": "Ben Thompson", "initials": "BT", "role": "Backend Engineer", "email": "ben.t@healthmesh.io", "on_call": False},
    ],
    "risk": [
        {"name": "James Park", "initials": "JP", "role": "Security Lead", "email": "james.p@healthmesh.io", "on_call": True},
        {"name": "Mia Chen", "initials": "MC", "role": "Security Engineer", "email": "mia.c@healthmesh.io", "on_call": False},
    ],
    "analytics": [
        {"name": "Natasha Williams", "initials": "NW", "role": "Data Engineering Manager", "email": "natasha.w@healthmesh.io", "on_call": True},
        {"name": "Omar Ali", "initials": "OA", "role": "Data Engineer", "email": "omar.a@healthmesh.io", "on_call": False},
        {"name": "Lena Fischer", "initials": "LF", "role": "Analytics Engineer", "email": "lena.f@healthmesh.io", "on_call": False},
    ],
}

ENVIRONMENTS = [
    {"id": "production", "name": "Production", "health_score": 91.4, "app_count": 13, "incident_count": 2, "status": "degraded"},
    {"id": "staging", "name": "Staging", "health_score": 96.8, "app_count": 13, "incident_count": 0, "status": "healthy"},
    {"id": "development", "name": "Development", "health_score": 98.5, "app_count": 13, "incident_count": 0, "status": "healthy"},
    {"id": "qa", "name": "QA", "health_score": 94.2, "app_count": 11, "incident_count": 0, "status": "healthy"},
]

APPLICATIONS = [
    {
        "id": "payments-api",
        "name": "Payments API",
        "description": "Core payment processing service handling charge, refund, and payment method operations.",
        "team_id": "payments",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P0",
        "health_score": 94.0,
        "uptime": 99.98,
        "latency_p99": 42.0,
        "rpm": 12400.0,
        "app_type": "API Service",
        "runtime": "Node.js 20",
        "version": "v2.14.1",
        "platform": "Kubernetes",
        "tags": ["payments", "critical", "pci-dss"],
        "incident_count": 0,
        "dependency_count": 6,
        "connector_count": 3,
        "trend": [91, 92, 90, 93, 94, 94, 95, 94, 93, 94, 94, 94],
        "owner_name": "Sarah Kim",
    },
    {
        "id": "customer-auth-service",
        "name": "Customer Auth Service",
        "description": "Identity and authentication service providing OAuth2, JWT, and MFA capabilities.",
        "team_id": "platform",
        "environment": "Production",
        "status": "warning",
        "criticality": "P0",
        "health_score": 71.0,
        "uptime": 99.91,
        "latency_p99": 310.0,
        "rpm": 8200.0,
        "app_type": "API Service",
        "runtime": "Go 1.22",
        "version": "v4.2.0",
        "platform": "Kubernetes",
        "tags": ["auth", "critical", "identity"],
        "incident_count": 1,
        "dependency_count": 4,
        "connector_count": 2,
        "trend": [85, 82, 79, 76, 74, 73, 71, 70, 71, 71, 71, 71],
        "owner_name": "Alex Chen",
    },
    {
        "id": "order-processing-gateway",
        "name": "Order Processing Gateway",
        "description": "Orchestrates order lifecycle from placement through fulfillment and delivery.",
        "team_id": "commerce",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P1",
        "health_score": 88.0,
        "uptime": 99.95,
        "latency_p99": 95.0,
        "rpm": 4100.0,
        "app_type": "API Service",
        "runtime": "Java 21",
        "version": "v3.8.2",
        "platform": "ECS",
        "tags": ["orders", "commerce", "gateway"],
        "incident_count": 0,
        "dependency_count": 8,
        "connector_count": 3,
        "trend": [84, 85, 86, 87, 87, 88, 88, 89, 88, 88, 88, 88],
        "owner_name": "Marcus Johnson",
    },
    {
        "id": "search-api",
        "name": "Search API",
        "description": "Full-text and semantic search service powering product discovery and filtering.",
        "team_id": "discovery",
        "environment": "Production",
        "status": "critical",
        "criticality": "P1",
        "health_score": 55.0,
        "uptime": 99.7,
        "latency_p99": 620.0,
        "rpm": 18500.0,
        "app_type": "API Service",
        "runtime": "Python 3.12",
        "version": "v1.9.5",
        "platform": "Kubernetes",
        "tags": ["search", "elasticsearch", "critical"],
        "incident_count": 1,
        "dependency_count": 5,
        "connector_count": 2,
        "trend": [80, 75, 70, 65, 63, 60, 57, 56, 55, 55, 55, 55],
        "owner_name": "Priya Patel",
    },
    {
        "id": "recommendation-engine",
        "name": "Recommendation Engine",
        "description": "ML-powered product recommendation service using collaborative filtering.",
        "team_id": "ml",
        "environment": "Production",
        "status": "warning",
        "criticality": "P1",
        "health_score": 78.0,
        "uptime": 99.85,
        "latency_p99": 185.0,
        "rpm": 22000.0,
        "app_type": "ML Service",
        "runtime": "Python 3.11",
        "version": "v2.3.0",
        "platform": "Kubernetes",
        "tags": ["ml", "recommendations", "personalization"],
        "incident_count": 1,
        "dependency_count": 4,
        "connector_count": 2,
        "trend": [88, 86, 84, 82, 80, 79, 78, 78, 78, 78, 78, 78],
        "owner_name": "David Wu",
    },
    {
        "id": "notification-engine",
        "name": "Notification Engine",
        "description": "Multi-channel notification service for email, SMS, push, and in-app alerts.",
        "team_id": "platform",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P1",
        "health_score": 92.0,
        "uptime": 99.93,
        "latency_p99": 55.0,
        "rpm": 6800.0,
        "app_type": "Service",
        "runtime": "Node.js 18",
        "version": "v3.1.4",
        "platform": "Kubernetes",
        "tags": ["notifications", "messaging"],
        "incident_count": 0,
        "dependency_count": 3,
        "connector_count": 2,
        "trend": [90, 91, 91, 92, 92, 93, 92, 92, 92, 92, 92, 92],
        "owner_name": "Jordan Blake",
    },
    {
        "id": "inventory-service",
        "name": "Inventory Service",
        "description": "Real-time inventory tracking, reservation, and stock management service.",
        "team_id": "commerce",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P1",
        "health_score": 96.0,
        "uptime": 99.97,
        "latency_p99": 28.0,
        "rpm": 3200.0,
        "app_type": "Service",
        "runtime": "Go 1.22",
        "version": "v1.6.3",
        "platform": "Kubernetes",
        "tags": ["inventory", "commerce"],
        "incident_count": 0,
        "dependency_count": 2,
        "connector_count": 2,
        "trend": [95, 95, 96, 96, 96, 96, 96, 97, 96, 96, 96, 96],
        "owner_name": "Ling Zhao",
    },
    {
        "id": "claims-portal-api",
        "name": "Claims Portal API",
        "description": "Insurance claims processing portal API with workflow automation.",
        "team_id": "commerce",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P1",
        "health_score": 89.0,
        "uptime": 99.92,
        "latency_p99": 118.0,
        "rpm": 1400.0,
        "app_type": "API Service",
        "runtime": "Java 17",
        "version": "v2.0.1",
        "platform": "ECS",
        "tags": ["claims", "portal"],
        "incident_count": 0,
        "dependency_count": 3,
        "connector_count": 2,
        "trend": [87, 87, 88, 88, 89, 89, 89, 89, 89, 89, 89, 89],
        "owner_name": "Fatima Hassan",
    },
    {
        "id": "fraud-detection-service",
        "name": "Fraud Detection Service",
        "description": "Real-time transaction fraud scoring using ML models and rule engines.",
        "team_id": "risk",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P0",
        "health_score": 97.0,
        "uptime": 99.99,
        "latency_p99": 18.0,
        "rpm": 15000.0,
        "app_type": "ML Service",
        "runtime": "Python 3.12",
        "version": "v4.1.2",
        "platform": "Kubernetes",
        "tags": ["fraud", "ml", "security", "critical"],
        "incident_count": 0,
        "dependency_count": 3,
        "connector_count": 3,
        "trend": [97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97],
        "owner_name": "James Park",
    },
    {
        "id": "reporting-hub",
        "name": "Reporting Hub",
        "description": "Business intelligence and analytics reporting service with scheduled exports.",
        "team_id": "analytics",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P2",
        "health_score": 90.0,
        "uptime": 99.89,
        "latency_p99": 250.0,
        "rpm": 800.0,
        "app_type": "Service",
        "runtime": "Python 3.11",
        "version": "v1.4.0",
        "platform": "ECS",
        "tags": ["reporting", "analytics", "bi"],
        "incident_count": 0,
        "dependency_count": 4,
        "connector_count": 2,
        "trend": [88, 89, 89, 90, 90, 90, 90, 90, 90, 90, 90, 90],
        "owner_name": "Natasha Williams",
    },
    {
        "id": "identity-service",
        "name": "Identity Service",
        "description": "Enterprise identity management with SSO, RBAC, and user provisioning.",
        "team_id": "platform",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P0",
        "health_score": 95.0,
        "uptime": 99.98,
        "latency_p99": 32.0,
        "rpm": 5600.0,
        "app_type": "Service",
        "runtime": "Go 1.22",
        "version": "v2.8.0",
        "platform": "Kubernetes",
        "tags": ["identity", "sso", "critical"],
        "incident_count": 0,
        "dependency_count": 2,
        "connector_count": 3,
        "trend": [94, 94, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95],
        "owner_name": "Riley Foster",
    },
    {
        "id": "customer-360-platform",
        "name": "Customer 360 Platform",
        "description": "Unified customer data platform aggregating profiles, behaviors, and interactions.",
        "team_id": "analytics",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P1",
        "health_score": 87.0,
        "uptime": 99.9,
        "latency_p99": 145.0,
        "rpm": 2200.0,
        "app_type": "Platform",
        "runtime": "Python 3.11",
        "version": "v1.2.3",
        "platform": "Kubernetes",
        "tags": ["customer-data", "cdp"],
        "incident_count": 0,
        "dependency_count": 5,
        "connector_count": 2,
        "trend": [84, 85, 85, 86, 87, 87, 87, 87, 87, 87, 87, 87],
        "owner_name": "Omar Ali",
    },
    {
        "id": "api-gateway",
        "name": "API Gateway",
        "description": "Edge API gateway handling routing, auth, rate limiting, and SSL termination.",
        "team_id": "platform",
        "environment": "Production",
        "status": "healthy",
        "criticality": "P0",
        "health_score": 98.0,
        "uptime": 99.99,
        "latency_p99": 12.0,
        "rpm": 45000.0,
        "app_type": "Gateway",
        "runtime": "NGINX / Envoy",
        "version": "v3.0.1",
        "platform": "Kubernetes",
        "tags": ["gateway", "critical", "infrastructure"],
        "incident_count": 0,
        "dependency_count": 10,
        "connector_count": 3,
        "trend": [98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98],
        "owner_name": "Alex Chen",
    },
]

APP_SIGNALS = {
    "payments-api": [
        {"category": "APM", "name": "P99 Latency", "value": "42", "unit": "ms", "status": "healthy", "trend": "down", "delta": "-3ms", "source": "Datadog"},
        {"category": "APM", "name": "Error Rate", "value": "0.04", "unit": "%", "status": "healthy", "trend": "stable", "delta": "+0.01%", "source": "Datadog"},
        {"category": "APM", "name": "Throughput", "value": "12.4K", "unit": "rpm", "status": "healthy", "trend": "up", "delta": "+400rpm", "source": "Datadog"},
        {"category": "Infra", "name": "CPU", "value": "62", "unit": "%", "status": "healthy", "trend": "stable", "delta": "+2%", "source": "Prometheus"},
        {"category": "Infra", "name": "Memory", "value": "71", "unit": "%", "status": "warning", "trend": "up", "delta": "+5%", "source": "Prometheus"},
        {"category": "Infra", "name": "Pod Restarts", "value": "2", "unit": "", "status": "warning", "trend": "up", "delta": "+2", "source": "Prometheus"},
        {"category": "Synthetic", "name": "Checkout Flow", "value": "1.2", "unit": "s", "status": "healthy", "trend": "stable", "delta": "+0.1s", "source": "Synthetic"},
        {"category": "Database", "name": "Query P99", "value": "8", "unit": "ms", "status": "healthy", "trend": "stable", "delta": "0ms", "source": "CloudWatch"},
        {"category": "Database", "name": "Connection Pool", "value": "74", "unit": "%", "status": "warning", "trend": "up", "delta": "+11%", "source": "CloudWatch"},
        {"category": "API", "name": "SLO Error Budget", "value": "82", "unit": "%", "status": "healthy", "trend": "down", "delta": "-3%", "source": "Datadog"},
    ],
    "customer-auth-service": [
        {"category": "APM", "name": "P99 Latency", "value": "310", "unit": "ms", "status": "warning", "trend": "up", "delta": "+45ms", "source": "Datadog"},
        {"category": "APM", "name": "Error Rate", "value": "0.18", "unit": "%", "status": "warning", "trend": "up", "delta": "+0.08%", "source": "Datadog"},
        {"category": "APM", "name": "Throughput", "value": "8.2K", "unit": "rpm", "status": "healthy", "trend": "stable", "delta": "-100rpm", "source": "Datadog"},
        {"category": "Infra", "name": "CPU", "value": "78", "unit": "%", "status": "warning", "trend": "up", "delta": "+12%", "source": "Prometheus"},
        {"category": "Infra", "name": "Memory", "value": "85", "unit": "%", "status": "critical", "trend": "up", "delta": "+18%", "source": "Prometheus"},
        {"category": "API", "name": "SLO Error Budget", "value": "61", "unit": "%", "status": "warning", "trend": "down", "delta": "-15%", "source": "Datadog"},
    ],
    "search-api": [
        {"category": "APM", "name": "P99 Latency", "value": "620", "unit": "ms", "status": "critical", "trend": "up", "delta": "+220ms", "source": "Datadog"},
        {"category": "APM", "name": "Error Rate", "value": "1.8", "unit": "%", "status": "critical", "trend": "up", "delta": "+1.2%", "source": "Datadog"},
        {"category": "APM", "name": "Throughput", "value": "18.5K", "unit": "rpm", "status": "healthy", "trend": "stable", "delta": "+500rpm", "source": "Datadog"},
        {"category": "Infra", "name": "CPU", "value": "91", "unit": "%", "status": "critical", "trend": "up", "delta": "+22%", "source": "Prometheus"},
        {"category": "Infra", "name": "Memory", "value": "88", "unit": "%", "status": "critical", "trend": "up", "delta": "+15%", "source": "Prometheus"},
        {"category": "API", "name": "SLO Error Budget", "value": "24", "unit": "%", "status": "critical", "trend": "down", "delta": "-31%", "source": "Datadog"},
    ],
}

APP_TRANSACTIONS = {
    "payments-api": [
        {"endpoint": "POST /v2/payments/charge", "rpm": 4820, "latency_p99": 38, "error_rate": 0.02, "apdex": 0.98, "status": "healthy"},
        {"endpoint": "GET /v2/payments/status/:id", "rpm": 3210, "latency_p99": 22, "error_rate": 0.00, "apdex": 0.99, "status": "healthy"},
        {"endpoint": "POST /v2/payments/refund", "rpm": 890, "latency_p99": 91, "error_rate": 0.12, "apdex": 0.91, "status": "healthy"},
        {"endpoint": "GET /v2/payments/history", "rpm": 1740, "latency_p99": 155, "error_rate": 0.31, "apdex": 0.85, "status": "warning"},
        {"endpoint": "POST /v2/payments/validate", "rpm": 6400, "latency_p99": 18, "error_rate": 0.00, "apdex": 0.99, "status": "healthy"},
        {"endpoint": "GET /v2/payments/methods", "rpm": 2100, "latency_p99": 445, "error_rate": 1.20, "apdex": 0.62, "status": "warning"},
    ],
    "customer-auth-service": [
        {"endpoint": "POST /auth/login", "rpm": 3400, "latency_p99": 280, "error_rate": 0.15, "apdex": 0.82, "status": "warning"},
        {"endpoint": "POST /auth/token/refresh", "rpm": 2800, "latency_p99": 340, "error_rate": 0.22, "apdex": 0.78, "status": "warning"},
        {"endpoint": "GET /auth/userinfo", "rpm": 1600, "latency_p99": 190, "error_rate": 0.08, "apdex": 0.88, "status": "healthy"},
        {"endpoint": "POST /auth/logout", "rpm": 980, "latency_p99": 120, "error_rate": 0.01, "apdex": 0.95, "status": "healthy"},
    ],
    "search-api": [
        {"endpoint": "GET /search/products", "rpm": 12400, "latency_p99": 680, "error_rate": 2.1, "apdex": 0.41, "status": "critical"},
        {"endpoint": "GET /search/autocomplete", "rpm": 4800, "latency_p99": 520, "error_rate": 1.4, "apdex": 0.55, "status": "critical"},
        {"endpoint": "POST /search/filters", "rpm": 1300, "latency_p99": 890, "error_rate": 2.8, "apdex": 0.32, "status": "critical"},
    ],
}

APP_LOG_PATTERNS = {
    "payments-api": [
        {"level": "error", "message": "ConnectionRefusedError: redis://payments-cache:6379", "count": 23, "first_seen": "2h ago", "last_seen": "4m ago"},
        {"level": "warn", "message": "Slow query detected: SELECT * FROM payment_ledger WHERE created_at > ?", "count": 88, "first_seen": "6h ago", "last_seen": "1m ago"},
        {"level": "error", "message": "UnhandledPromiseRejection: payment gateway timeout after 5000ms", "count": 4, "first_seen": "1h ago", "last_seen": "22m ago"},
        {"level": "warn", "message": "Retry attempt 3/3 for transaction tx_1Pd2e8LkdIwHu7ixy9JN", "count": 17, "first_seen": "3h ago", "last_seen": "8m ago"},
        {"level": "info", "message": "Rate limit applied: client_id=stripe-webhook (312 req/s)", "count": 312, "first_seen": "12h ago", "last_seen": "2m ago"},
    ],
    "customer-auth-service": [
        {"level": "error", "message": "JWT verification failed: token expired for user_id=u_8a2f9b", "count": 142, "first_seen": "1h ago", "last_seen": "30s ago"},
        {"level": "warn", "message": "Memory usage above 80% threshold, current: 85%", "count": 28, "first_seen": "45m ago", "last_seen": "2m ago"},
        {"level": "error", "message": "LDAP connection timeout: dc.corp.internal:389", "count": 7, "first_seen": "2h ago", "last_seen": "15m ago"},
    ],
    "search-api": [
        {"level": "error", "message": "Elasticsearch cluster unhealthy: status=yellow, unassigned_shards=4", "count": 89, "first_seen": "3h ago", "last_seen": "1m ago"},
        {"level": "error", "message": "Search query timeout after 2000ms for query_id=q_f4e2", "count": 234, "first_seen": "3h ago", "last_seen": "30s ago"},
        {"level": "warn", "message": "Circuit breaker OPEN for service: product-index", "count": 45, "first_seen": "2h ago", "last_seen": "5m ago"},
    ],
}

APP_INFRA_PODS = {
    "payments-api": [
        {"pod_name": "payments-api-d8f9b-xk2p1", "node": "node-03", "cpu_pct": 58, "mem_pct": 69, "restarts": 0, "age": "12d", "status": "Running"},
        {"pod_name": "payments-api-d8f9b-r7w4n", "node": "node-05", "cpu_pct": 71, "mem_pct": 74, "restarts": 1, "age": "12d", "status": "Running"},
        {"pod_name": "payments-api-d8f9b-tz8mn", "node": "node-02", "cpu_pct": 44, "mem_pct": 68, "restarts": 0, "age": "12d", "status": "Running"},
        {"pod_name": "payments-api-d8f9b-vq2xs", "node": "node-04", "cpu_pct": 88, "mem_pct": 81, "restarts": 2, "age": "3h", "status": "Running"},
    ],
    "customer-auth-service": [
        {"pod_name": "auth-svc-7c4d9-mn8p2", "node": "node-01", "cpu_pct": 78, "mem_pct": 85, "restarts": 3, "age": "2d", "status": "Running"},
        {"pod_name": "auth-svc-7c4d9-px3qr", "node": "node-06", "cpu_pct": 82, "mem_pct": 88, "restarts": 4, "age": "2d", "status": "Running"},
        {"pod_name": "auth-svc-7c4d9-ks7ty", "node": "node-02", "cpu_pct": 65, "mem_pct": 79, "restarts": 1, "age": "2d", "status": "Running"},
    ],
    "search-api": [
        {"pod_name": "search-api-2b8f1-qz9ws", "node": "node-07", "cpu_pct": 91, "mem_pct": 88, "restarts": 5, "age": "8h", "status": "Running"},
        {"pod_name": "search-api-2b8f1-lm4vn", "node": "node-08", "cpu_pct": 87, "mem_pct": 92, "restarts": 7, "age": "8h", "status": "CrashLoopBackOff"},
        {"pod_name": "search-api-2b8f1-pr6kx", "node": "node-03", "cpu_pct": 94, "mem_pct": 86, "restarts": 3, "age": "8h", "status": "Running"},
    ],
}

APP_DEPENDENCIES = {
    "payments-api": [
        {"dep_name": "order-processing-gateway", "dep_type": "Service", "status": "healthy", "latency": "12ms", "error_rate": "0.01%"},
        {"dep_name": "fraud-detection-service", "dep_type": "Service", "status": "healthy", "latency": "8ms", "error_rate": "0.00%"},
        {"dep_name": "payments-db", "dep_type": "Database", "status": "healthy", "latency": "4ms", "error_rate": "0.00%"},
        {"dep_name": "payments-cache", "dep_type": "Cache", "status": "warning", "latency": "18ms", "error_rate": "0.4%"},
        {"dep_name": "stripe-gateway", "dep_type": "External", "status": "healthy", "latency": "95ms", "error_rate": "0.02%"},
        {"dep_name": "notification-engine", "dep_type": "Service", "status": "healthy", "latency": "22ms", "error_rate": "0.00%"},
    ],
    "customer-auth-service": [
        {"dep_name": "identity-service", "dep_type": "Service", "status": "healthy", "latency": "15ms", "error_rate": "0.01%"},
        {"dep_name": "auth-db", "dep_type": "Database", "status": "healthy", "latency": "6ms", "error_rate": "0.00%"},
        {"dep_name": "redis-session", "dep_type": "Cache", "status": "warning", "latency": "25ms", "error_rate": "0.8%"},
        {"dep_name": "ldap-directory", "dep_type": "External", "status": "warning", "latency": "180ms", "error_rate": "2.1%"},
    ],
    "search-api": [
        {"dep_name": "elasticsearch-cluster", "dep_type": "Database", "status": "critical", "latency": "450ms", "error_rate": "5.2%"},
        {"dep_name": "product-catalog-db", "dep_type": "Database", "status": "healthy", "latency": "8ms", "error_rate": "0.00%"},
        {"dep_name": "search-cache", "dep_type": "Cache", "status": "warning", "latency": "35ms", "error_rate": "1.2%"},
        {"dep_name": "recommendation-engine", "dep_type": "Service", "status": "warning", "latency": "120ms", "error_rate": "0.9%"},
        {"dep_name": "vector-index", "dep_type": "Service", "status": "critical", "latency": "800ms", "error_rate": "8.4%"},
    ],
}

APP_ENDPOINTS = {
    "payments-api": [
        {"method": "POST", "path": "/v2/payments/charge", "status": "healthy", "rpm": 4820, "latency_p99": 38, "error_rate": 0.02, "version": "v2", "auth": "API Key"},
        {"method": "GET", "path": "/v2/payments/status/:id", "status": "healthy", "rpm": 3210, "latency_p99": 22, "error_rate": 0.00, "version": "v2", "auth": "JWT"},
        {"method": "POST", "path": "/v2/payments/refund", "status": "healthy", "rpm": 890, "latency_p99": 91, "error_rate": 0.12, "version": "v2", "auth": "API Key"},
        {"method": "GET", "path": "/v2/payments/history", "status": "warning", "rpm": 1740, "latency_p99": 155, "error_rate": 0.31, "version": "v2", "auth": "JWT"},
        {"method": "GET", "path": "/v2/payments/methods", "status": "warning", "rpm": 2100, "latency_p99": 445, "error_rate": 1.20, "version": "v2", "auth": "JWT"},
    ],
}

APP_HEALTH_SCORES = {
    "payments-api": [
        {"label": "D-27", "score": 91}, {"label": "D-26", "score": 92}, {"label": "D-25", "score": 90},
        {"label": "D-24", "score": 93}, {"label": "D-23", "score": 94}, {"label": "D-22", "score": 94},
        {"label": "D-21", "score": 95}, {"label": "D-20", "score": 94}, {"label": "D-19", "score": 93},
        {"label": "D-18", "score": 94}, {"label": "D-17", "score": 94}, {"label": "D-16", "score": 94},
        {"label": "D-15", "score": 93}, {"label": "D-14", "score": 95}, {"label": "D-13", "score": 94},
        {"label": "D-12", "score": 95}, {"label": "D-11", "score": 96}, {"label": "D-10", "score": 95},
        {"label": "D-9", "score": 94}, {"label": "D-8", "score": 95}, {"label": "D-7", "score": 94},
        {"label": "D-6", "score": 94}, {"label": "D-5", "score": 95}, {"label": "D-4", "score": 94},
        {"label": "D-3", "score": 93}, {"label": "D-2", "score": 94}, {"label": "D-1", "score": 94},
        {"label": "Today", "score": 94},
    ],
    "customer-auth-service": [
        {"label": "D-27", "score": 85}, {"label": "D-26", "score": 84}, {"label": "D-25", "score": 83},
        {"label": "D-24", "score": 82}, {"label": "D-23", "score": 81}, {"label": "D-22", "score": 80},
        {"label": "D-21", "score": 79}, {"label": "D-20", "score": 78}, {"label": "D-19", "score": 78},
        {"label": "D-18", "score": 77}, {"label": "D-17", "score": 76}, {"label": "D-16", "score": 75},
        {"label": "D-15", "score": 75}, {"label": "D-14", "score": 74}, {"label": "D-13", "score": 74},
        {"label": "D-12", "score": 73}, {"label": "D-11", "score": 73}, {"label": "D-10", "score": 72},
        {"label": "D-9", "score": 72}, {"label": "D-8", "score": 71}, {"label": "D-7", "score": 71},
        {"label": "D-6", "score": 71}, {"label": "D-5", "score": 71}, {"label": "D-4", "score": 70},
        {"label": "D-3", "score": 71}, {"label": "D-2", "score": 71}, {"label": "D-1", "score": 71},
        {"label": "Today", "score": 71},
    ],
    "search-api": [
        {"label": "D-27", "score": 80}, {"label": "D-26", "score": 78}, {"label": "D-25", "score": 76},
        {"label": "D-24", "score": 74}, {"label": "D-23", "score": 72}, {"label": "D-22", "score": 70},
        {"label": "D-21", "score": 68}, {"label": "D-20", "score": 65}, {"label": "D-19", "score": 64},
        {"label": "D-18", "score": 63}, {"label": "D-17", "score": 62}, {"label": "D-16", "score": 61},
        {"label": "D-15", "score": 61}, {"label": "D-14", "score": 60}, {"label": "D-13", "score": 59},
        {"label": "D-12", "score": 58}, {"label": "D-11", "score": 58}, {"label": "D-10", "score": 57},
        {"label": "D-9", "score": 57}, {"label": "D-8", "score": 56}, {"label": "D-7", "score": 56},
        {"label": "D-6", "score": 55}, {"label": "D-5", "score": 55}, {"label": "D-4", "score": 55},
        {"label": "D-3", "score": 55}, {"label": "D-2", "score": 55}, {"label": "D-1", "score": 55},
        {"label": "Today", "score": 55},
    ],
}

CONNECTOR_TEMPLATES = [
    {"id": "datadog", "name": "Datadog", "category": "APM", "description": "Full-stack observability with APM, metrics, logs, and synthetics.", "logo": "DD", "color": "#632CA6", "version": "v2", "fields": [{"key": "api_key", "label": "API Key", "type": "password", "required": True}, {"key": "app_key", "label": "App Key", "type": "password", "required": True}, {"key": "site", "label": "Site", "type": "select", "options": ["datadoghq.com", "datadoghq.eu"], "required": True}], "capabilities": ["APM", "Metrics", "Logs", "Synthetics", "Alerts"], "popular": True},
    {"id": "prometheus", "name": "Prometheus", "category": "Infra", "description": "Open-source metrics monitoring and alerting toolkit.", "logo": "PR", "color": "#E6522C", "version": "v2.48", "fields": [{"key": "endpoint", "label": "Prometheus URL", "type": "text", "required": True}, {"key": "auth_token", "label": "Bearer Token", "type": "password", "required": False}], "capabilities": ["Metrics", "Alerts", "Infrastructure"], "popular": True},
    {"id": "cloudwatch", "name": "AWS CloudWatch", "category": "Cloud", "description": "AWS monitoring and observability service.", "logo": "CW", "color": "#FF9900", "version": "API v2", "fields": [{"key": "access_key", "label": "Access Key ID", "type": "text", "required": True}, {"key": "secret_key", "label": "Secret Access Key", "type": "password", "required": True}, {"key": "region", "label": "AWS Region", "type": "text", "required": True}], "capabilities": ["Metrics", "Logs", "Alarms", "Infrastructure"], "popular": True},
    {"id": "splunk", "name": "Splunk Enterprise", "category": "Logs", "description": "Enterprise log management and SIEM platform.", "logo": "SP", "color": "#00A65A", "version": "v9.2", "fields": [{"key": "host", "label": "Splunk Host", "type": "text", "required": True}, {"key": "token", "label": "HEC Token", "type": "password", "required": True}, {"key": "index", "label": "Default Index", "type": "text", "required": False}], "capabilities": ["Logs", "Search", "Alerts", "SIEM"], "popular": False},
    {"id": "appdynamics", "name": "AppDynamics", "category": "APM", "description": "Cisco AppDynamics APM and business performance monitoring.", "logo": "AD", "color": "#1799D3", "version": "v24.1", "fields": [{"key": "controller_url", "label": "Controller URL", "type": "text", "required": True}, {"key": "account_name", "label": "Account Name", "type": "text", "required": True}, {"key": "api_client_id", "label": "API Client ID", "type": "text", "required": True}, {"key": "api_client_secret", "label": "API Client Secret", "type": "password", "required": True}], "capabilities": ["APM", "Infrastructure", "Business Transactions", "Flow Maps"], "popular": False},
    {"id": "grafana", "name": "Grafana Cloud", "category": "Infra", "description": "Open-source metrics, logs, and traces visualization platform.", "logo": "GR", "color": "#F46800", "version": "v10.2", "fields": [{"key": "grafana_url", "label": "Grafana URL", "type": "text", "required": True}, {"key": "service_account_token", "label": "Service Account Token", "type": "password", "required": True}], "capabilities": ["Dashboards", "Alerting", "Metrics", "Logs", "Traces"], "popular": True},
    {"id": "dynatrace", "name": "Dynatrace", "category": "APM", "description": "AI-powered full-stack observability platform.", "logo": "DY", "color": "#1496FF", "version": "v1.291", "fields": [{"key": "environment_id", "label": "Environment ID", "type": "text", "required": True}, {"key": "api_token", "label": "API Token", "type": "password", "required": True}], "capabilities": ["APM", "Infrastructure", "Digital Experience", "AI Insights"], "popular": False},
    {"id": "pagerduty", "name": "PagerDuty", "category": "Incident", "description": "Digital operations management and incident response platform.", "logo": "PD", "color": "#06AC38", "version": "API v2", "fields": [{"key": "api_key", "label": "API Key", "type": "password", "required": True}, {"key": "service_key", "label": "Integration Key", "type": "password", "required": False}], "capabilities": ["Incidents", "Alerting", "On-Call", "Escalation"], "popular": True},
    {"id": "kafka-monitor", "name": "Kafka Monitor", "category": "Messaging", "description": "Kafka cluster health and consumer lag monitoring.", "logo": "KF", "color": "#231F20", "version": "v3.6", "fields": [{"key": "bootstrap_servers", "label": "Bootstrap Servers", "type": "text", "required": True}, {"key": "consumer_group", "label": "Consumer Group", "type": "text", "required": False}], "capabilities": ["Metrics", "Consumer Lag", "Topic Health"], "popular": False},
    {"id": "db-monitor", "name": "Database Monitor", "category": "Database", "description": "Multi-database query performance and connection pool monitoring.", "logo": "DB", "color": "#336791", "version": "v1.4", "fields": [{"key": "connection_string", "label": "Connection String", "type": "password", "required": True}, {"key": "db_type", "label": "Database Type", "type": "select", "options": ["PostgreSQL", "MySQL", "Oracle", "MSSQL"], "required": True}], "capabilities": ["Query Performance", "Connection Pools", "Replication Lag", "Deadlocks"], "popular": False},
    {"id": "synthetic-health", "name": "Synthetic Health", "category": "Synthetic", "description": "Browser and API synthetic monitoring with global execution.", "logo": "SY", "color": "#0098D9", "version": "v2.0", "fields": [{"key": "api_key", "label": "API Key", "type": "password", "required": True}, {"key": "locations", "label": "Test Locations", "type": "multiselect", "options": ["us-east", "us-west", "eu-west", "ap-southeast"], "required": True}], "capabilities": ["Browser Tests", "API Tests", "Uptime Checks", "Global CDN"], "popular": False},
    {"id": "logicmonitor", "name": "LogicMonitor", "category": "Infra", "description": "Hybrid IT infrastructure monitoring platform.", "logo": "LM", "color": "#FF5733", "version": "v6.8", "fields": [{"key": "company", "label": "Company Name", "type": "text", "required": True}, {"key": "access_id", "label": "Access ID", "type": "text", "required": True}, {"key": "access_key", "label": "Access Key", "type": "password", "required": True}], "capabilities": ["Infrastructure", "Cloud", "Network", "Hybrid IT"], "popular": False},
]

CONNECTOR_INSTANCES = [
    {"id": "conn-datadog-prod", "template_id": "datadog", "name": "Datadog (Production)", "category": "APM", "environment": "Production", "status": "healthy", "health_pct": 99.0, "app_count": 42, "version": "v2.1.0", "last_sync": "2m ago", "metrics_count": "1,842", "config": {}},
    {"id": "conn-prometheus-prod", "template_id": "prometheus", "name": "Prometheus (Production)", "category": "Infra", "environment": "Production", "status": "healthy", "health_pct": 96.0, "app_count": 38, "version": "v2.48.0", "last_sync": "30s ago", "metrics_count": "3.2M", "config": {}},
    {"id": "conn-cloudwatch-aws", "template_id": "cloudwatch", "name": "CloudWatch (AWS)", "category": "Cloud", "environment": "Production", "status": "healthy", "health_pct": 98.0, "app_count": 29, "version": "API v2", "last_sync": "1m ago", "metrics_count": "847K", "config": {}},
    {"id": "conn-splunk-prod", "template_id": "splunk", "name": "Splunk Enterprise", "category": "Logs", "environment": "Production", "status": "warning", "health_pct": 71.0, "app_count": 15, "version": "v9.2.1", "last_sync": "12m ago", "metrics_count": "18.4B logs", "config": {}},
    {"id": "conn-appdynamics-prod", "template_id": "appdynamics", "name": "AppDynamics (Prod)", "category": "APM", "environment": "Production", "status": "healthy", "health_pct": 94.0, "app_count": 18, "version": "v24.1", "last_sync": "45s ago", "metrics_count": "426", "config": {}},
    {"id": "conn-grafana-cloud", "template_id": "grafana", "name": "Grafana Cloud", "category": "Infra", "environment": "Production", "status": "healthy", "health_pct": 92.0, "app_count": 22, "version": "v10.2", "last_sync": "3m ago", "metrics_count": "2.1M", "config": {}},
    {"id": "conn-dynatrace-staging", "template_id": "dynatrace", "name": "Dynatrace (Staging)", "category": "APM", "environment": "Staging", "status": "healthy", "health_pct": 97.0, "app_count": 12, "version": "v1.291", "last_sync": "1m ago", "metrics_count": "289", "config": {}},
    {"id": "conn-pagerduty-prod", "template_id": "pagerduty", "name": "PagerDuty", "category": "Incident", "environment": "Production", "status": "healthy", "health_pct": 100.0, "app_count": 34, "version": "API v2", "last_sync": "real-time", "metrics_count": "12 services", "config": {}},
    {"id": "conn-kafka-prod", "template_id": "kafka-monitor", "name": "Kafka Monitor", "category": "Messaging", "environment": "Production", "status": "healthy", "health_pct": 88.0, "app_count": 9, "version": "v3.6.0", "last_sync": "15s ago", "metrics_count": "47 topics", "config": {}},
    {"id": "conn-db-monitor-prod", "template_id": "db-monitor", "name": "Database Monitor", "category": "Database", "environment": "Production", "status": "warning", "health_pct": 68.0, "app_count": 17, "version": "v1.4.2", "last_sync": "8m ago", "metrics_count": "142 queries", "config": {}},
    {"id": "conn-synthetic-prod", "template_id": "synthetic-health", "name": "Synthetic Health", "category": "Synthetic", "environment": "Production", "status": "healthy", "health_pct": 95.0, "app_count": 24, "version": "v2.0.1", "last_sync": "5m ago", "metrics_count": "68 checks", "config": {}},
    {"id": "conn-logicmonitor-prod", "template_id": "logicmonitor", "name": "LogicMonitor", "category": "Infra", "environment": "Production", "status": "error", "health_pct": 0.0, "app_count": 0, "version": "v6.8", "last_sync": "2h ago", "metrics_count": "0", "config": {}},
]

HEALTH_RULES = [
    {"id": "rule-p99-latency", "name": "P99 Latency SLO", "metric": "latency_p99", "operator": "gt", "threshold": 300.0, "severity": "critical", "enabled": True, "scope": "P0 Services", "trigger_count": 12, "tags": ["latency", "slo", "apm"], "version": 3, "last_triggered": "14m ago", "description": "Triggers when P99 response time exceeds 300ms SLO threshold for P0 services"},
    {"id": "rule-error-rate", "name": "Error Rate Threshold", "metric": "error_rate", "operator": "gt", "threshold": 1.0, "severity": "critical", "enabled": True, "scope": "All Services", "trigger_count": 8, "tags": ["errors", "reliability"], "version": 2, "last_triggered": "1h ago", "description": "Fires when service error rate exceeds 1% over a 5-minute window"},
    {"id": "rule-memory-pressure", "name": "Memory Pressure Alert", "metric": "memory_pct", "operator": "gt", "threshold": 85.0, "severity": "warning", "enabled": True, "scope": "All Services", "trigger_count": 24, "tags": ["memory", "infra"], "version": 1, "last_triggered": "2m ago", "description": "Warns when container memory utilization exceeds 85% of limit"},
    {"id": "rule-cpu-saturation", "name": "CPU Saturation", "metric": "cpu_pct", "operator": "gt", "threshold": 90.0, "severity": "warning", "enabled": True, "scope": "All Services", "trigger_count": 6, "tags": ["cpu", "infra"], "version": 1, "last_triggered": "3h ago", "description": "Alerts when CPU utilization exceeds 90% sustained for 10 minutes"},
    {"id": "rule-throughput-drop", "name": "Request Throughput Drop", "metric": "throughput_pct_change", "operator": "lt", "threshold": -25.0, "severity": "warning", "enabled": True, "scope": "P0, P1 Services", "trigger_count": 3, "tags": ["throughput", "traffic"], "version": 2, "last_triggered": "2d ago", "description": "Detects significant traffic drops that could indicate upstream issues"},
    {"id": "rule-db-conn-pool", "name": "Database Connection Pool", "metric": "db_connection_pool_pct", "operator": "gt", "threshold": 80.0, "severity": "warning", "enabled": True, "scope": "Database Connectors", "trigger_count": 15, "tags": ["database", "connections"], "version": 1, "last_triggered": "4h ago", "description": "Warns when DB connection pool utilization exceeds 80% capacity"},
    {"id": "rule-slo-burn-rate", "name": "SLO Burn Rate (1h)", "metric": "slo_burn_rate_1h", "operator": "gt", "threshold": 14.4, "severity": "critical", "enabled": True, "scope": "P0, P1 Services", "trigger_count": 4, "tags": ["slo", "reliability", "burn-rate"], "version": 2, "last_triggered": "6h ago", "description": "Fires on fast SLO burn rate that would exhaust monthly error budget in <72h"},
    {"id": "rule-availability", "name": "Availability Below 99%", "metric": "availability", "operator": "lt", "threshold": 99.0, "severity": "critical", "enabled": True, "scope": "All Services", "trigger_count": 2, "tags": ["availability", "sla"], "version": 1, "last_triggered": "1w ago", "description": "Critical alert when service availability drops below 99% SLA commitment"},
]

INCIDENTS = [
    {
        "id": "INC-2847",
        "app_id": "search-api",
        "app_name": "Search API",
        "title": "search-api P99 latency exceeds SLO threshold (620ms)",
        "severity": "critical",
        "status": "active",
        "duration": "14m",
        "assignee": "Priya Patel",
        "ai_cause": "Elasticsearch cluster health degraded (yellow status) causing query routing to overloaded shards. Vector index service experiencing high error rate (8.4%), amplifying latency across all search operations.",
        "health_impact": "-39pts",
        "affected_deps": ["elasticsearch-cluster", "vector-index", "search-cache"],
        "timeline": [
            {"time": "14m ago", "event": "Incident created", "type": "created"},
            {"time": "13m ago", "event": "Assigned to Priya Patel", "type": "assigned"},
            {"time": "12m ago", "event": "Alert: P99 latency 620ms (threshold: 300ms)", "type": "alert"},
            {"time": "10m ago", "event": "Elasticsearch health: yellow → 4 unassigned shards", "type": "evidence"},
            {"time": "8m ago", "event": "Vector index circuit breaker OPEN", "type": "evidence"},
            {"time": "5m ago", "event": "Investigation in progress", "type": "update"},
        ],
        "started_at": "14m ago",
        "resolved_at": "",
    },
    {
        "id": "INC-2846",
        "app_id": "customer-auth-service",
        "app_name": "Customer Auth Service",
        "title": "auth-service elevated 5xx error rate (0.18%)",
        "severity": "warning",
        "status": "active",
        "duration": "1h 22m",
        "assignee": "Alex Chen",
        "ai_cause": "Memory pressure at 85% causing increased GC pause times. LDAP directory connection timeouts contributing to authentication failures. Pod restarts observed on auth-svc-7c4d9-px3qr.",
        "health_impact": "-14pts",
        "affected_deps": ["ldap-directory", "redis-session"],
        "timeline": [
            {"time": "1h 22m ago", "event": "Incident created", "type": "created"},
            {"time": "1h 20m ago", "event": "Auto-assigned to Alex Chen (on-call)", "type": "assigned"},
            {"time": "1h 15m ago", "event": "Alert: Error rate 0.18% (threshold: 0.1%)", "type": "alert"},
            {"time": "1h ago", "event": "Memory usage exceeded 80% on all pods", "type": "evidence"},
            {"time": "45m ago", "event": "LDAP timeout errors detected", "type": "evidence"},
            {"time": "30m ago", "event": "Pod restart observed: auth-svc-7c4d9-px3qr", "type": "evidence"},
            {"time": "15m ago", "event": "Scale-up initiated (3→4 replicas)", "type": "mitigation"},
        ],
        "started_at": "1h 22m ago",
        "resolved_at": "",
    },
    {
        "id": "INC-2844",
        "app_id": "recommendation-engine",
        "app_name": "Recommendation Engine",
        "title": "recommendation-engine degraded throughput (-18% vs baseline)",
        "severity": "degraded",
        "status": "active",
        "duration": "3h 5m",
        "assignee": "David Wu",
        "ai_cause": "Model serving latency increased after v2.3.0 deployment. Feature store cache hit rate dropped from 94% to 71%. Increased embedding computation causing CPU pressure.",
        "health_impact": "-10pts",
        "affected_deps": ["feature-store", "model-serving"],
        "timeline": [
            {"time": "3h 5m ago", "event": "Incident created automatically", "type": "created"},
            {"time": "3h ago", "event": "Throughput anomaly detected by AI", "type": "alert"},
            {"time": "2h 45m ago", "event": "Assigned to David Wu", "type": "assigned"},
            {"time": "2h 30m ago", "event": "v2.3.0 deployment identified as potential cause", "type": "evidence"},
            {"time": "1h ago", "event": "Cache warm-up strategy applied", "type": "mitigation"},
        ],
        "started_at": "3h 5m ago",
        "resolved_at": "",
    },
    {
        "id": "INC-2841",
        "app_id": "notification-engine",
        "app_name": "Notification Engine",
        "title": "notification-worker queue backlog (4.2K messages)",
        "severity": "warning",
        "status": "resolved",
        "duration": "42m",
        "assignee": "Jordan Blake",
        "ai_cause": "Kafka consumer lag spike due to external email provider throttling. Queue backlog cleared after dynamic scaling of consumer pods.",
        "health_impact": "-8pts",
        "affected_deps": ["kafka-cluster", "email-provider"],
        "timeline": [
            {"time": "6h ago", "event": "Incident created", "type": "created"},
            {"time": "5h 58m ago", "event": "Queue depth alert fired (4.2K)", "type": "alert"},
            {"time": "5h 40m ago", "event": "Consumer pods scaled: 2→5", "type": "mitigation"},
            {"time": "5h 18m ago", "event": "Queue depth normalized", "type": "resolved"},
        ],
        "started_at": "6h ago",
        "resolved_at": "5h 18m ago",
    },
    {
        "id": "INC-2839",
        "app_id": "customer-auth-service",
        "app_name": "Customer Auth Service",
        "title": "catalog-service cache miss spike (92% miss rate)",
        "severity": "warning",
        "status": "resolved",
        "duration": "1h 12m",
        "assignee": "Marcus Johnson",
        "ai_cause": "Redis cache eviction after memory limit breach caused cold cache state. Cache warming script executed to restore hit rates.",
        "health_impact": "-12pts",
        "affected_deps": ["redis-cache", "catalog-db"],
        "timeline": [
            {"time": "1d ago", "event": "Incident created", "type": "created"},
            {"time": "23h ago", "event": "Cache miss alert fired (92%)", "type": "alert"},
            {"time": "22h 30m ago", "event": "Cache warming initiated", "type": "mitigation"},
            {"time": "22h ago", "event": "Hit rate restored to 87%", "type": "resolved"},
        ],
        "started_at": "1d ago",
        "resolved_at": "23h ago",
    },
]

ALERTS = [
    {"id": "ALT-1247", "app_id": "search-api", "app_name": "Search API", "rule_name": "P99 Latency SLO", "metric": "latency_p99", "value": "620ms", "threshold": "300ms", "severity": "critical", "status": "firing", "fired_at": "14m ago", "environment": "Production"},
    {"id": "ALT-1246", "app_id": "customer-auth-service", "app_name": "Customer Auth Service", "rule_name": "Memory Pressure Alert", "metric": "memory_pct", "value": "85%", "threshold": "85%", "severity": "warning", "status": "firing", "fired_at": "1h ago", "environment": "Production"},
    {"id": "ALT-1245", "app_id": "search-api", "app_name": "Search API", "rule_name": "Error Rate Threshold", "metric": "error_rate", "value": "1.8%", "threshold": "1%", "severity": "critical", "status": "firing", "fired_at": "2h ago", "environment": "Production"},
    {"id": "ALT-1244", "app_id": "payments-api", "app_name": "Payments API", "rule_name": "Database Connection Pool", "metric": "db_connection_pool_pct", "value": "74%", "threshold": "80%", "severity": "warning", "status": "pending", "fired_at": "3h ago", "environment": "Production"},
    {"id": "ALT-1243", "app_id": "recommendation-engine", "app_name": "Recommendation Engine", "rule_name": "Request Throughput Drop", "metric": "throughput_pct_change", "value": "-18%", "threshold": "-25%", "severity": "warning", "status": "firing", "fired_at": "3h ago", "environment": "Production"},
]

DEPENDENCY_NODES = [
    {"id": "api-gateway", "label": "API Gateway", "node_type": "gateway", "status": "healthy", "latency": "12ms", "error_rate": "0.01%", "rps": "45K", "uptime": "99.99%", "version": "v3.0.1", "team": "Platform", "x": 400, "y": 50},
    {"id": "auth-service", "label": "Auth Service", "node_type": "service", "status": "warning", "latency": "310ms", "error_rate": "0.18%", "rps": "8.2K", "uptime": "99.91%", "version": "v4.2.0", "team": "Platform", "x": 200, "y": 180},
    {"id": "payments-api", "label": "Payments API", "node_type": "service", "status": "healthy", "latency": "42ms", "error_rate": "0.04%", "rps": "12.4K", "uptime": "99.98%", "version": "v2.14.1", "team": "Payments", "x": 100, "y": 320},
    {"id": "catalog-service", "label": "Catalog Service", "node_type": "service", "status": "healthy", "latency": "28ms", "error_rate": "0.00%", "rps": "18K", "uptime": "99.97%", "version": "v2.1.0", "team": "Commerce", "x": 300, "y": 320},
    {"id": "search-api", "label": "Search API", "node_type": "service", "status": "critical", "latency": "620ms", "error_rate": "1.8%", "rps": "18.5K", "uptime": "99.70%", "version": "v1.9.5", "team": "Discovery", "x": 500, "y": 320},
    {"id": "recommendation-engine", "label": "Recommendation Engine", "node_type": "service", "status": "warning", "latency": "185ms", "error_rate": "0.22%", "rps": "22K", "uptime": "99.85%", "version": "v2.3.0", "team": "ML", "x": 700, "y": 320},
    {"id": "db-primary", "label": "DB Primary", "node_type": "database", "status": "healthy", "latency": "4ms", "error_rate": "0.00%", "rps": "12K", "uptime": "99.99%", "version": "PostgreSQL 15", "team": "Platform", "x": 200, "y": 480},
    {"id": "redis-cluster", "label": "Redis Cluster", "node_type": "cache", "status": "healthy", "latency": "0.8ms", "error_rate": "0.00%", "rps": "280K", "uptime": "99.99%", "version": "Redis 7.2", "team": "Platform", "x": 400, "y": 480},
    {"id": "event-bus", "label": "Event Bus (Kafka)", "node_type": "queue", "status": "healthy", "latency": "8ms", "error_rate": "0.01%", "rps": "180K", "uptime": "99.98%", "version": "Kafka 3.6", "team": "Platform", "x": 600, "y": 480},
    {"id": "stripe-api", "label": "Stripe API", "node_type": "external", "status": "healthy", "latency": "95ms", "error_rate": "0.02%", "rps": "4.8K", "uptime": "99.95%", "version": "API v3", "team": "External", "x": 100, "y": 480},
]

DEPENDENCY_EDGES = [
    {"source_id": "api-gateway", "target_id": "auth-service", "status": "warning", "latency": "310ms", "label": ""},
    {"source_id": "api-gateway", "target_id": "catalog-service", "status": "healthy", "latency": "28ms", "label": ""},
    {"source_id": "api-gateway", "target_id": "search-api", "status": "critical", "latency": "620ms", "label": ""},
    {"source_id": "api-gateway", "target_id": "payments-api", "status": "healthy", "latency": "42ms", "label": ""},
    {"source_id": "api-gateway", "target_id": "recommendation-engine", "status": "warning", "latency": "185ms", "label": ""},
    {"source_id": "payments-api", "target_id": "db-primary", "status": "healthy", "latency": "4ms", "label": ""},
    {"source_id": "payments-api", "target_id": "redis-cluster", "status": "healthy", "latency": "0.8ms", "label": ""},
    {"source_id": "payments-api", "target_id": "stripe-api", "status": "healthy", "latency": "95ms", "label": ""},
    {"source_id": "payments-api", "target_id": "event-bus", "status": "healthy", "latency": "8ms", "label": ""},
    {"source_id": "auth-service", "target_id": "db-primary", "status": "healthy", "latency": "4ms", "label": ""},
    {"source_id": "auth-service", "target_id": "redis-cluster", "status": "warning", "latency": "25ms", "label": ""},
    {"source_id": "search-api", "target_id": "redis-cluster", "status": "healthy", "latency": "0.8ms", "label": ""},
]

AI_INSIGHTS = [
    {
        "id": "ins-001",
        "app_id": "search-api",
        "app_name": "Search API",
        "insight_type": "anomaly",
        "priority": "high",
        "title": "Anomalous EU traffic surge detected on search-api",
        "description": "Search API is experiencing a 94% confidence anomaly: EU region traffic has increased 340% above baseline over the past 45 minutes. This is causing Elasticsearch cluster degradation and P99 latency to spike to 620ms.",
        "confidence": 0.94,
        "impact": "High - 18.5K rpm affected",
        "recommendation": "Scale Elasticsearch cluster to handle increased EU load. Review CDN routing rules to balance traffic distribution. Consider enabling query result caching for top EU search patterns.",
        "signals": ["latency_p99", "error_rate", "throughput", "elasticsearch_health"],
        "what_changed": "Traffic from EU-West-1 increased from baseline 2.1K rpm to 9.3K rpm at 14:22 UTC. Elasticsearch shard rebalancing triggered by uneven load distribution.",
        "generated_at": "8m ago",
    },
    {
        "id": "ins-002",
        "app_id": "customer-auth-service",
        "app_name": "Customer Auth Service",
        "insight_type": "prediction",
        "priority": "high",
        "title": "Memory exhaustion predicted for auth-service in ~2 hours",
        "description": "ML model predicts auth-service will reach OOM condition within 2 hours based on current memory growth rate (+3.2% per hour). Pod will likely restart, causing 15-30 seconds of auth failures.",
        "confidence": 0.87,
        "impact": "High - Auth failures for all users",
        "recommendation": "Immediately increase memory limits from 512Mi to 768Mi. Investigate memory leak introduced in v4.2.0 deployment (heap dump analysis recommended). Consider rollback to v4.1.8.",
        "signals": ["memory_pct", "gc_pause_time", "heap_used", "pod_restarts"],
        "what_changed": "Memory growth rate increased after v4.2.0 deployment 2 days ago. GC pause times trending up: 120ms → 340ms P99.",
        "generated_at": "15m ago",
    },
    {
        "id": "ins-003",
        "app_id": "payments-api",
        "app_name": "Payments API",
        "insight_type": "correlation",
        "priority": "medium",
        "title": "GC pause correlation with payment latency spikes detected",
        "description": "Strong correlation (r=0.91) found between JVM GC pause events and P99 latency spikes on the payments service. Every GC pause exceeding 150ms causes a measurable latency increase on the payments/methods endpoint.",
        "confidence": 0.91,
        "impact": "Medium - Intermittent latency spikes",
        "recommendation": "Tune JVM GC settings: switch to G1GC or ZGC for lower pause times. Review heap allocation patterns. Consider G1GC pause target of 50ms.",
        "signals": ["gc_pause_duration", "latency_p99", "heap_usage", "throughput"],
        "what_changed": "GC pause frequency increased from 2/min to 8/min after traffic growth this week. Heap pressure from increased payment volume.",
        "generated_at": "1h ago",
    },
    {
        "id": "ins-004",
        "app_id": "customer-360-platform",
        "app_name": "Customer 360 Platform",
        "insight_type": "optimization",
        "priority": "low",
        "title": "Customer 360 caching opportunity: 67% of queries are cache-eligible",
        "description": "Analysis of query patterns shows 67% of Customer 360 API requests query the same 500 customer profiles. Implementing a read-through cache layer could reduce database load by 60% and cut P99 latency from 145ms to ~40ms.",
        "confidence": 0.82,
        "impact": "Low - Performance optimization",
        "recommendation": "Implement Redis read-through cache for customer profile queries with 5-minute TTL. Estimated 3x latency improvement and 60% reduction in database load.",
        "signals": ["query_patterns", "cache_hit_rate", "db_load", "latency_p99"],
        "what_changed": "Traffic analysis over 7 days reveals highly repetitive query patterns concentrated on top-tier customer profiles.",
        "generated_at": "2h ago",
    },
    {
        "id": "ins-005",
        "app_id": "payments-api",
        "app_name": "Payments API",
        "insight_type": "capacity",
        "priority": "medium",
        "title": "Payments-api Redis connection pool approaching limit at current growth rate",
        "description": "Redis connection pool utilization is at 74% and growing at 2% per day. At the current trajectory, the pool will reach 80% warning threshold in ~3 days and 90% critical threshold in ~8 days.",
        "confidence": 0.89,
        "impact": "Medium - Connection exhaustion risk",
        "recommendation": "Increase Redis connection pool size from 100 to 150 connections. Implement connection pooling best practices. Review connection leak patterns in payments code.",
        "signals": ["redis_connection_pool_pct", "redis_latency", "throughput", "error_rate"],
        "what_changed": "Connection pool growth correlated with 18% increase in payment volume over the past week. Pool size not adjusted since Q3.",
        "generated_at": "3h ago",
    },
]

DASHBOARD_SNAPSHOTS = []
for i in range(24):
    base = 91 + 3 * math.sin(i * math.pi / 12)
    DASHBOARD_SNAPSHOTS.append({
        "hour_label": f"{i:02d}:00",
        "health_score": round(base + random.uniform(-1, 1), 1),
        "incidents": max(0, 2 + round(random.uniform(-1, 2))),
        "alerts": max(0, 5 + round(random.uniform(-2, 3))),
        "healthy_apps": 9,
        "degraded_apps": 3,
        "critical_apps": 1,
    })

TREND_DATA_MONTHLY = [
    {"period_type": "monthly", "label": "Oct", "health_score": 88.2, "availability": 99.82, "incidents": 18, "latency": 112.0, "error_rate": 0.42, "mttr": 47.0, "mttd": 12.0},
    {"period_type": "monthly", "label": "Nov", "health_score": 89.1, "availability": 99.85, "incidents": 15, "latency": 108.0, "error_rate": 0.38, "mttr": 42.0, "mttd": 10.0},
    {"period_type": "monthly", "label": "Dec", "health_score": 87.4, "availability": 99.79, "incidents": 21, "latency": 118.0, "error_rate": 0.51, "mttr": 55.0, "mttd": 14.0},
    {"period_type": "monthly", "label": "Jan", "health_score": 90.5, "availability": 99.88, "incidents": 12, "latency": 102.0, "error_rate": 0.31, "mttr": 38.0, "mttd": 9.0},
    {"period_type": "monthly", "label": "Feb", "health_score": 91.2, "availability": 99.91, "incidents": 10, "latency": 98.0, "error_rate": 0.28, "mttr": 34.0, "mttd": 8.0},
    {"period_type": "monthly", "label": "Mar", "health_score": 90.8, "availability": 99.89, "incidents": 11, "latency": 101.0, "error_rate": 0.30, "mttr": 36.0, "mttd": 8.5},
    {"period_type": "monthly", "label": "Apr", "health_score": 91.4, "availability": 99.91, "incidents": 9, "latency": 97.0, "error_rate": 0.27, "mttr": 32.0, "mttd": 7.5},
]

TREND_DATA_WEEKLY = []
for i in range(28):
    day = 28 - i
    base_score = 90 + 2 * math.sin(i * math.pi / 14)
    TREND_DATA_WEEKLY.append({
        "period_type": "weekly",
        "label": f"D-{day}",
        "health_score": round(base_score + random.uniform(-2, 2), 1),
        "availability": round(99.8 + random.uniform(0, 0.19), 2),
        "incidents": max(0, round(random.uniform(0, 2))),
        "latency": round(95 + random.uniform(-10, 20), 1),
        "error_rate": round(random.uniform(0.1, 0.5), 2),
        "mttr": round(30 + random.uniform(-10, 20), 1),
        "mttd": round(8 + random.uniform(-2, 5), 1),
    })

MAINTENANCE_WINDOWS = [
    {"id": "mw-001", "title": "Elasticsearch Cluster Rebalancing", "description": "Scheduled shard rebalancing and index optimization for search cluster", "start_time": "2026-04-10T02:00:00Z", "end_time": "2026-04-10T04:00:00Z", "affected_apps": ["search-api", "recommendation-engine"], "status": "scheduled", "created_by": "Priya Patel"},
    {"id": "mw-002", "title": "Auth Service Memory Limit Update", "description": "Updating memory limits and applying JVM tuning for auth service pods", "start_time": "2026-04-09T22:00:00Z", "end_time": "2026-04-09T23:00:00Z", "affected_apps": ["customer-auth-service"], "status": "active", "created_by": "Alex Chen"},
    {"id": "mw-003", "title": "Database Schema Migration v2.1", "description": "Payments database schema migration for new ledger table indexes", "start_time": "2026-04-11T03:00:00Z", "end_time": "2026-04-11T04:30:00Z", "affected_apps": ["payments-api"], "status": "scheduled", "created_by": "Carlos Mendez"},
    {"id": "mw-004", "title": "Redis Cluster Upgrade", "description": "Upgrading Redis cluster from 7.2 to 7.4 for improved memory management", "start_time": "2026-04-08T01:00:00Z", "end_time": "2026-04-08T02:30:00Z", "affected_apps": ["payments-api", "customer-auth-service", "catalog-service"], "status": "completed", "created_by": "Jordan Blake"},
]

SLA_SETTINGS = [
    {"id": "sla-001", "app_id": "payments-api", "name": "Payments API Availability SLA", "target_pct": 99.95, "current_pct": 99.98, "error_budget_remaining": 92.0, "period": "30d", "status": "healthy"},
    {"id": "sla-002", "app_id": "customer-auth-service", "name": "Auth Service Availability SLA", "target_pct": 99.9, "current_pct": 99.91, "error_budget_remaining": 45.0, "period": "30d", "status": "warning"},
    {"id": "sla-003", "app_id": "search-api", "name": "Search API Performance SLA", "target_pct": 99.5, "current_pct": 99.7, "error_budget_remaining": 24.0, "period": "30d", "status": "warning"},
    {"id": "sla-004", "app_id": "fraud-detection-service", "name": "Fraud Detection Availability SLA", "target_pct": 99.99, "current_pct": 99.99, "error_budget_remaining": 98.0, "period": "30d", "status": "healthy"},
    {"id": "sla-005", "app_id": "api-gateway", "name": "API Gateway Availability SLA", "target_pct": 99.99, "current_pct": 99.99, "error_budget_remaining": 97.0, "period": "30d", "status": "healthy"},
]

AUDIT_LOGS = [
    {"user_name": "Alex Chen", "user_email": "alex.chen@healthmesh.io", "action": "UPDATE", "resource_type": "ConnectorInstance", "resource_id": "conn-splunk-prod", "resource_name": "Splunk Enterprise", "details": "Updated HEC token configuration", "ip_address": "10.0.1.42", "timestamp": "2026-04-09T14:22:18Z"},
    {"user_name": "Sarah Kim", "user_email": "sarah.kim@healthmesh.io", "action": "CREATE", "resource_type": "HealthRule", "resource_id": "rule-p99-latency", "resource_name": "P99 Latency SLO", "details": "Created new P99 latency rule for P0 services", "ip_address": "10.0.1.55", "timestamp": "2026-04-09T13:45:02Z"},
    {"user_name": "Priya Patel", "user_email": "priya.p@healthmesh.io", "action": "CREATE", "resource_type": "MaintenanceWindow", "resource_id": "mw-001", "resource_name": "Elasticsearch Cluster Rebalancing", "details": "Scheduled maintenance for shard rebalancing", "ip_address": "10.0.2.18", "timestamp": "2026-04-09T11:30:00Z"},
    {"user_name": "System", "user_email": "system@healthmesh.io", "action": "TRIGGER", "resource_type": "Alert", "resource_id": "ALT-1247", "resource_name": "P99 Latency SLO - search-api", "details": "Alert auto-triggered: latency_p99=620ms exceeded threshold=300ms", "ip_address": "127.0.0.1", "timestamp": "2026-04-09T14:58:00Z"},
    {"user_name": "Marcus Johnson", "user_email": "marcus.j@healthmesh.io", "action": "UPDATE", "resource_type": "Application", "resource_id": "order-processing-gateway", "resource_name": "Order Processing Gateway", "details": "Updated team ownership metadata", "ip_address": "10.0.1.77", "timestamp": "2026-04-09T10:15:44Z"},
    {"user_name": "David Wu", "user_email": "david.wu@healthmesh.io", "action": "UPDATE", "resource_type": "Application", "resource_id": "recommendation-engine", "resource_name": "Recommendation Engine", "details": "Deployed v2.3.0 to production", "ip_address": "10.0.3.22", "timestamp": "2026-04-09T08:00:01Z"},
]

APP_SETTINGS_DATA = [
    {"key": "org_name", "value": "Acme Corporation", "category": "general", "description": "Organization display name"},
    {"key": "default_environment", "value": "Production", "category": "general", "description": "Default environment for new apps"},
    {"key": "default_timezone", "value": "UTC", "category": "general", "description": "Default timezone for timestamps"},
    {"key": "health_refresh_interval", "value": "60", "category": "general", "description": "Health score refresh interval in seconds"},
    {"key": "alert_cooldown_minutes", "value": "5", "category": "alerting", "description": "Minimum minutes between repeat alerts"},
    {"key": "incident_auto_assign", "value": "true", "category": "incidents", "description": "Auto-assign incidents to on-call engineer"},
    {"key": "data_retention_days", "value": "90", "category": "data", "description": "Days to retain metric history"},
    {"key": "ai_insights_enabled", "value": "true", "category": "ai", "description": "Enable AI-powered insights generation"},
]
